name: buddy
description: Softwareprojekt FH Wedel 2022
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts:
  firebase_auth:
  firebase_core:
  firebase_storage:
  google_sign_in:
  shared_preferences:
  random_string:
  cloud_firestore:
  image_picker:
  image_cropper:
  material_dialogs:

  cupertino_icons: ^1.0.2
  readmore: ^2.1.0
  swipe_cards: ^1.0.0
  uuid: ^3.0.6
  nfc_in_flutter: ^2.0.5
  intl: ^0.17.0
  flutter_toggle_tab: ^1.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

fonts:
  - family: SansSerif
    fonts:
      - asset:
           - assets/OpenSans-Medium.ttf

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/OpenSans-Medium.ttf
    - assets/top1.png
    - assets/top2.png
    - assets/bottom1.png
    - assets/bottom2.png
    - assets/f_logo.png
    - assets/otto.png
